USE [master]
GO

/****** Object:  Database [Microcreditos]    Script Date: 6/9/2021 20:44:24 ******/
CREATE DATABASE [Microcreditos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Microcreditos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Microcreditos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Microcreditos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Microcreditos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Microcreditos] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Microcreditos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Microcreditos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Microcreditos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Microcreditos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Microcreditos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Microcreditos] SET ARITHABORT OFF 
GO

ALTER DATABASE [Microcreditos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Microcreditos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Microcreditos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Microcreditos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Microcreditos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Microcreditos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Microcreditos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Microcreditos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Microcreditos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Microcreditos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Microcreditos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Microcreditos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Microcreditos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Microcreditos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Microcreditos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Microcreditos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Microcreditos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Microcreditos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Microcreditos] SET  MULTI_USER 
GO

ALTER DATABASE [Microcreditos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Microcreditos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Microcreditos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Microcreditos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Microcreditos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Microcreditos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Microcreditos] SET  READ_WRITE 
GO


